/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-03-27 11:02:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package com.vsc.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipInputStream;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.ServletInputStream;

import org.apache.commons.fileupload.FileItem;
import org.apache.commons.fileupload.FileItemFactory;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.PrintSetup;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;















import intellsoft.db.DBUtil;
import intellsoft.db.RecordSet;
import report.util.JasperUtil;
import report.util.XmlJasperUtil;
import upload.UploadListener;
import upload.MonitoredDiskFileItemFactory;
import upload.ZipUtil;


public final class DRGroup {
	public int ReportCount=0;
	public int PageCount=0;
	public int PageNumber=0;
	String groupName;
	Row[] _DefGH;
	Row[] _DefGF;
	String[] groupField;
	HashMap groupValue;
	String[] grVar;
	String[] grExprType;
	int[] grCount;
	float[] grPrev;
	float[] grCurr;
	
	boolean firstTime=true;
	public void addGroup(String name,Row[] defGH,Row[] defGF) {
		groupName=name;
		_DefGH=defGH;
		_DefGF=defGF;
		//detechGroupExpression
		
	}
	public boolean compare(Object ob1,Object ob2) {
		return true;
	}
	public void evaluate(RecordSet rsData) {
		for(int i=0;i<grVar.length;i++) {
			String exprType=grExprType[i];
			if(exprType.equalsIgnoreCase("max")) {
				
			}
		}
	}
	public int checkGroupChange(RecordSet rsData) {
		//0=not change,1=first group,2=change group
		int change=0;
		for(int i=0;i<groupField.length;i++) {
			String val=""+rsData.getString(groupField[i]);
			String oldVal=""+groupValue.get(groupField[i]);
			if(oldVal.equals(val)) {
				
			}
			else {
				if(firstTime) {
					change=1;
					firstTime=false;
				}
				else {
					change=2;
				}
				groupValue.put(groupField[i], val);
			}
		}
		return change;
	}
}
